baseURL = "https://www.zwyssig.info/"
title = "Zwyssig Informatik GmbH"
publishDir = "docs"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = false
disableKinds = ["taxonomy", "term"]

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML"]
