[de]
label = "Deutsch"
locale = "de-CH"
weight = 1
contentDir = "content/de"
title = "Zwyssig Informatik GmbH"

[en]
label = "English"
locale = "en"
weight = 2
contentDir = "content/en"
title = "Zwyssig Informatik GmbH"
