[[main]]
name = "Home"
pageRef = "/"
weight = 1
[[main]]
name = "Angebot"
pageRef = "/angebot/"
weight = 2
[[main]]
name = "Lösungen"
pageRef = "/loesungen/"
weight = 3
[[main]]
name = "Methode"
pageRef = "/methode/"
weight = 4
[[main]]
name = "Kern-Kompetenzen"
pageRef = "/kompetenzen/"
weight = 5
[[main]]
name = "Firma"
pageRef = "/firma/"
weight = 6
