[[main]]
name = "Home"
pageRef = "/"
weight = 1
[[main]]
name = "Angebot"
pageRef = "/angebot"
weight = 2
[[main]]
name = "Kompetenzen"
pageRef = "/kompetenzen"
weight = 3
[[main]]
name = "Firma"
pageRef = "/firma"
weight = 4
