[[main]]
name = "Home"
pageRef = "/"
weight = 1
[[main]]
name = "Services"
pageRef = "/angebot/"
weight = 2
[[main]]
name = "Solutions"
pageRef = "/loesungen/"
weight = 3
[[main]]
name = "Method"
pageRef = "/methode/"
weight = 4
[[main]]
name = "Expertise"
pageRef = "/kompetenzen/"
weight = 5
[[main]]
name = "Company"
pageRef = "/firma/"
weight = 6
