[company]
name = "Zwyssig Informatik GmbH"
street = "Seebüelstrasse 38"
city = "CH-8185 Winkel"
phone = "+41 79 468 55 77"
phoneHref = "+41794685577"
email = "sales@zwyssig.info"
register = "CHE-112.480.156"
registerOffice = "Zürich"
