slogan = "Listening. Understanding. Delivering."

[company]
name = "Zwyssig Informatik GmbH"
street = "Kirchweg 45a"
city = "CH-8196 Wil ZH"
phone = "+41 79 468 55 77"
phoneHref = "+41794685577"
email = "sales@zwyssig.info"
register = "CHE-112.480.156"
registerOffice = "Zürich"
